// Generated by CoffeeScript 1.6.3
(function() {
  var app;

  app = angular.module('LoadFrock', []);

  app.service('MasterService', function() {
    var MasterService, ws;
    ws = new WebSocket('ws://localhost:5577/');
    MasterService = {
      connected: false,
      actions: {},
      register_action: function(action, callback) {
        return this.actions[action] = callback;
      },
      run_action: function(action, data) {
        if (data === void 0) {
          data = {};
        }
        data['action'] = action;
        return ws.send(JSON.stringify(data));
      }
    };
    ws.onopen = function() {
      MasterService.connected = true;
      return MasterService.run_action('connect');
    };
    ws.onmessage = function(msg) {
      var data;
      if (msg) {
        data = JSON.parse(msg.data);
        if (data['action']) {
          return MasterService.actions[data['action']](data);
        }
      }
    };
    return MasterService;
  });

  app.controller('FrockBodyCtrl', function($scope, $rootScope, MasterService) {
    $scope.status = MasterService.connected;
    $scope.echo_stuff = function() {
      return MasterService.run_action('echo', {
        'message': 'stuff'
      });
    };
    return MasterService.register_action('echo', function(data) {
      return console.log('Master told us to echo', data);
    });
  });

}).call(this);
